### ISSUE TITLE
If expireAt key is null, session is unusable: "Can't get expireAt from redis"

### ISSUE THREAD

**Issue by sheax0r** [zinin/tomcat-redis-session#5]
I recently encountered this stacktrace in a production application that I am involved in maintaining:

java.lang.IllegalStateException: Can't get expireAt from redis.
  ru.zinin.redis.RedisHttpSession.getExpireAt(RedisHttpSession.java:717)
  ru.zinin.redis.RedisHttpSession.renewAll(RedisHttpSession.java:457)
  ru.zinin.redis.RedisHttpSession.access(RedisHttpSession.java:509)
  org.apache.catalina.connector.Request.doGetSession(Request.java:2868)

The user who encountered the error was unable to login, and needed to clear their cookies (ie: get a new session token) in order to make the error go away. I'm not sure how the session got into this state, since from briefly looking at the code, it looks like this key should only ever get set when in a transaction that creates the session.

I also thought that maybe the redis server had evicted keys due to running out of memory, but the INFO command told me this was not the case. So - somehow this key became null, and the session was rendered unusable but still existed.

Perhaps instead of just raising an exception, the session should also be destroyed if a fatal error indicating that it is unusable occurs? Then errors like this wouldn't continue to persist until key expiry (or client-side destruction of cookies).

**Comment by nagasrinu-canvass** [comment]
Hi,

I have also faced the same Issue 

and I am using following dependencies 
spring-data-redis --- 1.5.0.RELEASE
spring-session-data-redis --- 1.0.0.RELEASE

can some one help me to fix this.

I found that there is new versions available to the above dependencies, will it help if I use the new versions?
